### ISSUE TITLE
P-A

### ISSUE THREAD

**Issue by notebook-t** [notebook-t/br.tiringo.comandosLinux#10]
![Screenshot_20241001-171805-629.png](https://github.com/user-attachments/assets/50b57c05-e2dd-44a0-9f30-7621feb7f037)

**Comment by notebook-t** [comment]
![Screenshot_20241001-173911-927.png](https://github.com/user-attachments/assets/163d1ea5-3028-435c-978b-50189f399145)

![Screenshot_20241001-170500-705.png](https://github.com/user-attachments/assets/e4daedc5-2e7b-41d6-a823-a93950424834)

![Screenshot_20241001-171805-629.png](https://github.com/user-attachments/assets/2399d6c6-3ddb-41fb-8a4a-98464e5db0b0)

![Screenshot_20241001-180924-242.png](https://github.com/user-attachments/assets/a84e990d-479e-402b-b2f5-8420510e7a69)

**Comment by notebook-t** [comment]
![Screenshot_20241001-173911-927.png](https://github.com/user-attachments/assets/163d1ea5-3028-435c-978b-50189f399145)

![Screenshot_20241001-170500-705.png](https://github.com/user-attachments/assets/e4daedc5-2e7b-41d6-a823-a93950424834)

![Screenshot_20241001-171805-629.png](https://github.com/user-attachments/assets/2399d6c6-3ddb-41fb-8a4a-98464e5db0b0)

![Screenshot_20241001-180924-242.png](https://github.com/user-attachments/assets/a84e990d-479e-402b-b2f5-8420510e7a69)

![Screenshot_20240930-164232.png](https://github.com/user-attachments/assets/0caff4d6-cbfa-4893-b266-7416b75a180e)

![Screenshot_20241001-173911-927.png](https://github.com/user-attachments/assets/b6ae8f32-b852-4622-a541-d77c65a14357)

**Comment by 231414806** [comment]
Here is a simple footnote[^1].

A footnote can also have multiple lines[^2].

[^1]: My reference.
[^2]: To add line breaks within a footnote, prefix new lines with 2 spaces.
  This is a second line.
